# bind = MODS, key, dispatcher, params
bind = $mainMod+SHIFT,P, exec,hyprpicker --autocopy # Color Picker


$out = ~/Pictures/Screenshots
# Screenshot a monitor
bind = ,PRINT, exec, hyprshot --mode active --mode output --output-folder $out
# Screenshot a window
bind = $mainMod+SHIFT, PRINT, exec, hyprshot --mode window --output-folder $out
# Screenshot a region
bind = $mainMod+CTRL, PRINT, exec, hyprshot --mode region --output-folder $out


